// snapshot.json is generated by the scraper as the merge of every file in
// data/seasons/ -- the durable archive -- plus the run's metadata. The site
// reads the merged view; the archive is what guarantees a season survives CYO
// dropping it from its dropdowns.
import snapshot from '~~/data/snapshot.json'
// The annual CYO calendar is a separate, hand-refreshed artefact. Keeping it out
// of the snapshot means re-extracting the PDF does not require re-scraping CYO.
import cyoCalendar from '~~/data/cyo-calendar.json'
// Accumulating video archive: without a YouTube API key each scrape only sees
// the 15 most recent uploads, so the list is built up rather than replaced.
import videoArchive from '~~/data/videos.json'
import overrides from '~~/data/overrides.json'
// Hand-entered parish dates (evaluations, meetings). Kept out of the CYO PDF
// extract so a calendar refresh does not wipe them.
import parishCalendar from '~~/data/parish-events.json'

export interface Side { name: string; score: number | null }
export interface TournamentRef { name: string; round: number | null; host: string | null; notes: string | null }
export interface Game {
  id: string; date: string; startTime: string | null; endTime: string | null
  venue: string | null; status: string | null; league: string | null; division: string | null
  team1: Side; team2: Side; season: string; teamIds: string[]
  /** 1 or 2 if that side hosted; null at a neutral site. Resolved from the venue. */
  homeSide?: 1 | 2 | null
  /** Present only on bracket games from Athletics_Tournaments.aspx. */
  tournament?: TournamentRef
}
export interface Team {
  id: string; org: string; orgName: string; season: string; seasonId: string
  name: string; parish: string; league: string; division: string
  coaches: string[]; gameIds: string[]
}
export interface StandingRow { division: string | null; team: string; wins: number; losses: number; draws: number }
export interface StandingsTable { season: string; league: string; rows: StandingRow[] }
export interface CalendarEvent { date: string; title: string; category?: 'sport' | 'blackout' | 'other' }
export interface ParishEvent {
  date: string
  title: string
  startTime: string | null
  endTime: string | null
  venue: string | null
  /** Matches a Parents-page sport label when one exists. */
  sport: string
  note: string | null
}

export interface Snapshot {
  scrapedAt: string; source: string; seasons: string[]
  /** Seasons CYO no longer lists, kept from the archive. */
  retiredSeasons?: string[]
  teams: Team[]; games: Game[]; standings: StandingsTable[]
}

type CoachOverrides = {
  coachReplace?: Record<string, Record<string, string>>
  coachesByTeamId?: Record<string, string[]>
}

function applyCoachOverrides (teams: Team[]) {
  const replBySeason = (overrides as CoachOverrides).coachReplace ?? {}
  const byTeamId = (overrides as CoachOverrides).coachesByTeamId ?? {}
  return teams.map(t => {
    let coaches = t.coaches
    const repl = replBySeason[t.season]
    if (repl) coaches = coaches.map(c => (c in repl ? repl[c]! : c))
    if (t.id in byTeamId) coaches = byTeamId[t.id]!
    return coaches.every((c, i) => c === t.coaches[i]) ? t : { ...t, coaches }
  })
}

const rawSnapshot = snapshot as unknown as Snapshot
export const data: Snapshot = {
  ...rawSnapshot,
  teams: applyCoachOverrides(rawSnapshot.teams)
}

/** Every season we hold, newest first. */
export const archivedSeasons = [...new Set(data.teams.map(t => t.season))]
  .sort((a, b) => b.localeCompare(a))
/** True for a season CYO has stopped publishing — we are the only copy. */
export const isRetired = (season: string) => (data.retiredSeasons ?? []).includes(season)
export const calendarEvents = (cyoCalendar as { events: CalendarEvent[] }).events
export const parishEvents = (parishCalendar as { events: ParishEvent[] }).events
  .slice()
  .sort((a, b) => a.date.localeCompare(b.date) || (a.startTime ?? '').localeCompare(b.startTime ?? ''))

/** Names of every team belonging to our parishes, for highlighting in fixtures. */
const ourTeamNames = new Set(data.teams.map(t => t.name))
export const isOurs = (name: string) => ourTeamNames.has(name)

/** "2026 Fall Girls Volleyball" -> { year, term, sport }. */
export function seasonParts (season: string) {
  const m = /^(\S+)\s+(Fall|Spring|Winter)?\s*(.*)$/.exec(season)
  return { year: m?.[1] ?? '', term: m?.[2] ?? '', sport: (m?.[3] ?? season).trim() }
}

export const TODAY = new Date().toISOString().slice(0, 10)

export function formatDate (iso: string, opts: Intl.DateTimeFormatOptions = {}) {
  const [y, m, d] = iso.split('-').map(Number)
  return new Date(y!, m! - 1, d!).toLocaleDateString('en-US', {
    weekday: 'short', month: 'short', day: 'numeric', ...opts
  })
}

export function formatTime (hhmm: string | null) {
  if (!hhmm) return ''
  const [h, m] = hhmm.split(':').map(Number)
  const ampm = h! < 12 ? 'AM' : 'PM'
  return `${((h! + 11) % 12) + 1}:${String(m).padStart(2, '0')} ${ampm}`
}

/** Result of a game from the perspective of one of our teams. */
export function outcome (game: Game, teamName: string) {
  if (game.status !== 'Played') return null
  const mine = game.team1.name === teamName ? game.team1 : game.team2
  const theirs = game.team1.name === teamName ? game.team2 : game.team1
  if (mine.score == null || theirs.score == null) return null
  return {
    us: mine.score,
    them: theirs.score,
    opponent: theirs.name,
    result: mine.score > theirs.score ? 'W' : mine.score < theirs.score ? 'L' : 'T'
  }
}

export const gameById = new Map(data.games.map(g => [g.id, g]))
export const teamById = new Map(data.teams.map(t => [t.id, t]))

export function teamGames (team: Team): Game[] {
  return team.gameIds.map(id => gameById.get(id)!).filter(Boolean)
}

/**
 * Regular-season record by default. CYO standings count league play only, and
 * this number sits next to the standings table, so folding bracket games in
 * would make the two disagree. Pass 'tournament' for the bracket record.
 */
export function teamRecord (team: Team, scope: 'league' | 'tournament' = 'league') {
  let w = 0, l = 0, t = 0
  for (const g of teamGames(team)) {
    if ((scope === 'tournament') !== Boolean(g.tournament)) continue
    const o = outcome(g, team.name)
    if (!o) continue
    if (o.result === 'W') w++; else if (o.result === 'L') l++; else t++
  }
  return { w, l, t }
}

/** Seasons that still have games today or later, newest activity first. */
export function activeSeasons () {
  const seasons = [...new Set(data.teams.map(t => t.season))]
  return seasons
    .map(season => {
      const w = seasonWindow(season)
      return {
        season,
        window: w,
        lastDate: w?.end ?? '',
        active: Boolean(w) && TODAY >= w!.start && TODAY <= w!.end
      }
    })
    .sort((a, b) => b.lastDate.localeCompare(a.lastDate))
}

/**
 * Split a fixture into "our side" and the opponent. Both sides can be ours
 * when two parish teams meet, in which case team1 is treated as ours.
 */
export function sides (game: Game) {
  const oursFirst = isOurs(game.team1.name)
  const ours = oursFirst ? game.team1 : game.team2
  const opponent = oursFirst ? game.team2 : game.team1
  return { ours, opponent, derby: isOurs(game.team1.name) && isOurs(game.team2.name) }
}

/** Lyons / Crusaders home sites in CYO venue strings (Lourdes campus or Scecina). */
const CAMPUS_VENUE = /\b(lourdes|scecina)\b/i

export function isCampusVenue (venue: string | null) {
  return Boolean(venue && CAMPUS_VENUE.test(venue))
}

export function campusVenueLabel (venue: string | null) {
  if (!venue) return ''
  if (/scecina/i.test(venue)) return 'Scecina'
  if (/lourdes/i.test(venue)) return 'Lourdes'
  return venue
}

/** Upcoming or any fixture involving our teams at Lourdes or Scecina. */
export function isCampusHomeGame (game: Game) {
  if (!isOurs(game.team1.name) && !isOurs(game.team2.name)) return false
  return isCampusVenue(game.venue)
}

/** 'w' | 'l' | 't' | null, from our side's point of view. */
export function resultClass (game: Game) {
  if (game.status !== 'Played') return null
  const { ours, opponent } = sides(game)
  if (ours.score == null || opponent.score == null) return null
  return ours.score > opponent.score ? 'w' : ours.score < opponent.score ? 'l' : 't'
}

export interface Video { id: string; title: string; published: string; date: string; url: string; thumb: string }

/** "2026 Fall Girls Volleyball" -> "Volleyball". */
export function sportOf (season: string) {
  return season
    .replace(/^\d{4}(-\d{4})?\s+/, '')
    .replace(/^(Fall|Spring|Winter)\s+/, '')
    .replace(/\b(Boys|Girls|CO-ED|Co-Ed|High School|&)\b/gi, '')
    .replace(/\s+/g, ' ')
    .trim() || season
}

/**
 * Fixed hue per sport, never cycled and never reassigned when a filter hides a
 * sport. Hues are slots 1/2/3/4 of the validated categorical theme.
 *
 * Validated with the dataviz palette validator (`--pairs all`, light + dark) for
 * every set of sports that can share one month view. At most three sports ever
 * co-occur in a month, and the live triples -- {Volleyball, Kickball, Football}
 * and {Volleyball, Kickball, Soccer} -- both pass all checks in both modes.
 * Cross country has no CYO fixtures; its hue is used for CYO meet dates.
 */
export const SPORT_ORDER = ['Volleyball', 'Football', 'Kickball', 'Soccer', 'Cross Country'] as const
export const SPORT_VAR: Record<string, string> = {
  Volleyball: '--sport-1',
  Football: '--sport-2',
  Kickball: '--sport-3',
  Soccer: '--sport-4',
  'Cross Country': '--sport-5'
}
export const sportVar = (sport: string) => SPORT_VAR[sport] ?? '--sport-other'

/** Sports that actually have fixtures, in the fixed hue order. */
export function sportsWithGames () {
  const present = new Set(data.games.map(g => sportOf(g.season)))
  return SPORT_ORDER.filter(s => present.has(s)).concat(
    [...present].filter(s => !SPORT_ORDER.includes(s as never)).sort()
  )
}

export function isCrossCountryEvent (e: { title: string }) {
  return /^\s*cross country\b/i.test(e.title)
}

/** Fixtures plus Cross Country when CYO lists a meet or we field a team. */
export function sportsForCalendar () {
  const present = new Set(sportsWithGames())
  const hasCc = data.teams.some(t => sportOf(t.season) === 'Cross Country')
    || sportEvents.some(isCrossCountryEvent)
  if (hasCc) present.add('Cross Country')
  return SPORT_ORDER.filter(s => present.has(s)).concat(
    [...present].filter(s => !SPORT_ORDER.includes(s as never)).sort()
  )
}

export const videos = videoArchive as unknown as Video[]
export const channel = (data as unknown as { channel?: { url: string; streams: string } }).channel
  ?? { url: 'https://www.youtube.com/@ollindyAVclub', streams: 'https://www.youtube.com/@ollindyAVclub/streams' }

/** Broadcasts published on a given day — the A/V club posts a stream same-day. */
export function videosOn (date: string) {
  return videos.filter(v => v.date === date)
}

/**
 * The A/V club films concerts, Masses and graduations too, so a same-day game
 * is only a meaningful association when the title actually names a sport.
 */
const GAME_TITLE = /\b(CYO|volleyball|football|kickball|basketball|soccer|baseball|softball|cross ?country|wrestling|track|vs\.?)\b/i
export const isGameVideo = (v: Video) => GAME_TITLE.test(v.title)

/** Same-day broadcasts that look like game coverage. */
export function gameVideosOn (date: string) {
  return videosOn(date).filter(isGameVideo)
}

/**
 * The CYO calendar carries office closures, board meetings, chess and music
 * dates too. This site only shows the sporting ones: start dates, registration
 * deadlines, practices, playoffs and championships.
 */
export const sportEvents = calendarEvents.filter(e => e.category === 'sport')
/** Explicit "No CYO Sports" days — useful, but off by default as there are many. */
export const blackoutEvents = calendarEvents.filter(e => e.category === 'blackout')

export interface ParentSportSeason {
  sport: string
  start: string
  end: string
  /** True when CYO does not publish a season-end date and we inferred one. */
  endEstimated: boolean
  /** Parish fee estimate; blank in overrides until published. */
  costEstimate: string
}

function parentSportCostEstimate (sport: string) {
  const map = (overrides as { parentSportCostEstimates?: Record<string, string> }).parentSportCostEstimates
  return map?.[sport]?.trim() ?? ''
}

function cyoSportEvent (titleMatch: RegExp, which: 'first' | 'last' = 'first') {
  const hits = sportEvents.filter(e => titleMatch.test(e.title))
  if (!hits.length) return null
  hits.sort((a, b) => a.date.localeCompare(b.date))
  return which === 'first' ? hits[0]! : hits[hits.length - 1]!
}

function addDays (iso: string, days: number) {
  const [y, m, d] = iso.split('-').map(Number)
  const dt = new Date(y!, m! - 1, d!)
  dt.setDate(dt.getDate() + days)
  return `${dt.getFullYear()}-${String(dt.getMonth() + 1).padStart(2, '0')}-${String(dt.getDate()).padStart(2, '0')}`
}

interface MirroredSportWindow {
  start: string
  end: string
  /** Fixtures from the latest archived season — current school year has none yet. */
  fromPriorYear: boolean
}

/** Min/max fixture dates for a sport: current school year first, else latest archived season. */
function mirroredWindowForSport (
  seasonMatch: (season: string) => boolean,
  anchorYear: number
): MirroredSportWindow | null {
  const schoolStart = `${anchorYear}-08-01`
  const schoolEnd = `${anchorYear + 1}-05-31`
  const inSchoolYearWindow = (iso: string) => iso >= schoolStart && iso <= schoolEnd

  const currentGames = data.games.filter(g => seasonMatch(g.season) && inSchoolYearWindow(g.date))
  if (currentGames.length) {
    const dates = currentGames.map(g => g.date).sort()
    return { start: dates[0]!, end: dates[dates.length - 1]!, fromPriorYear: false }
  }

  let bestSeason = ''
  let bestLast = ''
  for (const g of data.games) {
    if (!seasonMatch(g.season)) continue
    if (g.date > bestLast) {
      bestLast = g.date
      bestSeason = g.season
    }
  }
  if (!bestSeason) return null
  const dates = data.games.filter(g => g.season === bestSeason).map(g => g.date).sort()
  return {
    start: dates[0]!,
    end: dates[dates.length - 1]!,
    fromPriorYear: true
  }
}

/** Inferred season ends when CYO only publishes a start date and we have no fixtures. */
function estimateParentSeasonEnd (sport: string, start: string): string {
  const before = (iso: string) => addDays(iso, -1)
  const ev = (re: RegExp, which: 'first' | 'last' = 'first') => cyoSportEvent(re, which)?.date

  switch (sport) {
    case 'Boys grade school basketball':
      return before(ev(/^Boys Basketball Tournament Begins$/i) ?? addDays(start, 51))
    case 'Girls grade school basketball':
      return addDays(start, 77)
    case 'Boys volleyball':
      return before(ev(/^Track & Field Begins$/i) ?? addDays(start, 56))
    case 'Kickball (spring)':
    case 'Co-ed soccer (spring)':
      return ev(/Memorial Day/i) ?? addDays(start, 49)
    default:
      return addDays(start, 56)
  }
}

/** CYO grade-school sport windows from the annual calendar, Aug → May. */
export function parentSportSeasons (): ParentSportSeason[] {
  const anchorYear = Number(
    sportEvents.map(e => e.date).filter(d => Number(d.slice(5, 7)) >= 8).sort()[0]?.slice(0, 4)
    ?? TODAY.slice(0, 4))
  const inSchoolYear = (iso: string) => {
    const y = Number(iso.slice(0, 4))
    const m = Number(iso.slice(5, 7))
    if (m >= 8) return y === anchorYear
    return y === anchorYear + 1 && m <= 5
  }

  const defs: {
    sport: string
    seasonMatch: (season: string) => boolean
    start: RegExp
    end: RegExp | null
    endWhich?: 'first' | 'last'
  }[] = [
    {
      sport: 'Kickball (fall)',
      seasonMatch: s => /fall/i.test(s) && /kickball/i.test(s),
      start: /^Kickball Begins$/i,
      end: null
    },
    {
      sport: 'Football',
      seasonMatch: s => /fall/i.test(s) && /football/i.test(s),
      start: /Football Opening Weekend/i,
      end: /Cadet Football Championship/i
    },
    {
      sport: 'Cross country',
      seasonMatch: s => /cross country/i.test(s),
      start: /^Cross Country Begins$/i,
      end: /Cross Country Championship/i
    },
    {
      sport: 'Girls volleyball',
      seasonMatch: s => /fall/i.test(s) && /girls/i.test(s) && /volleyball/i.test(s),
      start: /Girls Grade School Volleyball Begins/i,
      end: /Girls Volleyball City Championships/i
    },
    {
      sport: 'Boys grade school basketball',
      seasonMatch: s => /basketball/i.test(s) && /boys/i.test(s),
      start: /^Boys Grade School Basketball Begins$/i,
      end: null
    },
    {
      sport: 'Girls grade school basketball',
      seasonMatch: s => /basketball/i.test(s) && /girls/i.test(s),
      start: /^Girls Grade School Basketball Begins/i,
      end: null
    },
    {
      sport: 'Boys wrestling',
      seasonMatch: s => /wrestling/i.test(s),
      start: /^Boys Wrestling Begins$/i,
      end: /Boys Wrestling City Tournament/i
    },
    {
      sport: 'Boys volleyball',
      seasonMatch: s => /spring/i.test(s) && /volleyball/i.test(s),
      start: /^Boys Grade School Volleyball Begins$/i,
      end: null
    },
    {
      sport: 'Track & field',
      seasonMatch: s => /track/i.test(s),
      start: /^Track & Field Begins$/i,
      end: /Track & Field Championships @ Marian University/i
    },
    {
      sport: 'Kickball (spring)',
      seasonMatch: s => /spring/i.test(s) && /kickball/i.test(s),
      start: /^Kickball, Softball, Baseball, & Co-Ed Soccer Begin/i,
      end: null
    },
    {
      sport: 'Co-ed soccer (spring)',
      seasonMatch: s => /spring/i.test(s) && /soccer/i.test(s),
      start: /^Kickball, Softball, Baseball, & Co-Ed Soccer Begin/i,
      end: null
    }
  ]

  const rows: ParentSportSeason[] = []
  for (const d of defs) {
    const s = cyoSportEvent(d.start, 'first')
    if (!s || !inSchoolYear(s.date)) continue

    const cyoEnd = d.end ? cyoSportEvent(d.end, d.endWhich ?? 'last') : null
    const mirror = mirroredWindowForSport(d.seasonMatch, anchorYear)

    const costEstimate = parentSportCostEstimate(d.sport)

    // No fixtures yet this school year — use CYO Aug→May dates, not last year's mirror.
    if (mirror?.fromPriorYear) {
      const start = s.date
      const end = cyoEnd?.date ?? estimateParentSeasonEnd(d.sport, start)
      rows.push({
        sport: d.sport,
        start,
        end,
        endEstimated: !cyoEnd,
        costEstimate
      })
      continue
    }

    const start = mirror?.start && mirror.start < s.date ? mirror.start : s.date
    const end = mirror?.end ?? cyoEnd?.date ?? estimateParentSeasonEnd(d.sport, start)
    rows.push({
      sport: d.sport,
      start,
      end,
      endEstimated: !mirror?.end && !cyoEnd,
      costEstimate
    })
  }
  return rows
}

export function parentSeasonActive (row: ParentSportSeason) {
  if (TODAY < row.start) return false
  return TODAY <= row.end
}

export function parentSeasonFinished (row: ParentSportSeason) {
  if (TODAY < row.start) return false
  return TODAY > row.end
}

/**
 * CYO league order: oldest grade first, A before B before C, with the
 * youngest (4th / 3-4) last. CYO itself returns leagues alphabetically, which
 * puts "4th Girls" above "Cadet A Girls".
 */
export function leagueRank (league: string) {
  const l = league || ''
  const level =
    /cadet/i.test(l) ? 0
      : /\b(56|5\/6)\b/.test(l) ? 100
        : /\b(4th|4|34|3\/4|3rd)\b/.test(l) ? 200
          : 300
  const tier = /\bA\b/.test(l) ? 0 : /\bB\b/.test(l) ? 1 : /\bC\b/.test(l) ? 2 : 3
  return level + tier
}

export const byLeague = <T extends { league: string }>(a: T, b: T) =>
  leagueRank(a.league) - leagueRank(b.league) || a.league.localeCompare(b.league)

/**
 * How a fixture is written, always from our point of view: our team leads, and
 * the separator says where it is played.
 *
 *   home    OL Lourdes-Blue  vs  Holy Spirit-Yellow
 *   away    OL Lourdes-Blue  @   St. Roch-Gold
 *   neutral OL Lourdes-Blue  vs  Johnson Co.-White
 *
 * CYO's own team1/team2 order is not home/away, so it is never used for this.
 */
export function matchup (game: Game) {
  const { ours, opponent, derby } = sides(game)
  const homeTeam = game.homeSide === 1 ? game.team1 : game.homeSide === 2 ? game.team2 : null

  // Two of our own teams meeting: lead with whoever is hosting.
  if (derby) {
    const first = homeTeam ?? game.team1
    const second = first === game.team1 ? game.team2 : game.team1
    return { first, second, sep: 'vs' as const, at: false, home: Boolean(homeTeam), neutral: !homeTeam }
  }

  const away = Boolean(homeTeam) && homeTeam !== ours
  return {
    first: ours,
    second: opponent,
    sep: (away ? '@' : 'vs') as 'vs' | '@',
    at: away,
    home: Boolean(homeTeam) && homeTeam === ours,
    neutral: !homeTeam
  }
}

/**
 * CYO suffixes every team with a colour ("OL Lourdes-Blue"). Opponents drop
 * that suffix on this site. Our own colour is kept only when we field more
 * than one team in the same season and league.
 */
const ourTeamsPerLeague = new Map<string, Set<string>>()
for (const t of data.teams) {
  const k = `${t.season}|${t.league}`
  if (!ourTeamsPerLeague.has(k)) ourTeamsPerLeague.set(k, new Set())
  ourTeamsPerLeague.get(k)!.add(t.name)
}

const COLOUR_SUFFIX = /-(Black|Blue|Gold|Gray|Green|Maroon|Navy|Purple|Red|Royal|Silver|White|Yellow)$/i
const dropColour = (name: string) => name.replace(COLOUR_SUFFIX, '')

export function displayTeam (name: string, season?: string | null, league?: string | null) {
  if (!isOurs(name)) return dropColour(name)
  if (!season || !league) return name
  const siblings = ourTeamsPerLeague.get(`${season}|${league}`)
  return siblings && siblings.size > 1 ? name : dropColour(name)
}

/** Convenience for a team record, which always carries its own context. */
export const teamLabel = (t: Team) => displayTeam(t.name, t.season, t.league)

const SPORT_IN_TEXT = /(volleyball|football|basketball|kickball|soccer|softball|baseball|wrestling|track|cross ?country)/i
const normSport = (s: string) => s.toLowerCase().replace(/\s+/g, '')

/** Years a season label can span: "2026-2027 Boys Basketball" covers both. */
function seasonYears (season: string) {
  const m = /^(\d{4})(?:-(\d{4}))?/.exec(season)
  return m ? [m[1], m[2]].filter(Boolean) as string[] : []
}

/**
 * First and last date of a season. Normally the fixture list bounds it; for a
 * sport with no fixtures we read the CYO calendar's "<sport> Begins" and
 * "<sport> Championship" entries instead.
 */
export function seasonWindow (season: string): { start: string; end: string } | null {
  const dates = data.games.filter(g => g.season === season).map(g => g.date).sort()
  if (dates.length) return { start: dates[0]!, end: dates[dates.length - 1]! }

  const sport = normSport(sportOf(season))
  const years = seasonYears(season)
  const mine = sportEvents.filter(e => {
    const m = SPORT_IN_TEXT.exec(e.title)
    return m && normSport(m[1]!) === sport &&
      (!years.length || years.includes(e.date.slice(0, 4)))
  })
  const start = mine.filter(e => /\bbegins?\b/i.test(e.title)).map(e => e.date).sort()[0]
  const end = mine.filter(e => /championship|\bfinals?\b|playoffs?/i.test(e.title))
    .map(e => e.date).sort().pop()
  if (!start && !end) return null
  return { start: start ?? end!, end: end ?? start! }
}
